### ISSUE TITLE
How to generate the occlusion masks in the dataset?

### ISSUE THREAD

**Issue by Trav1slaflame** [maximiliangilles/MetaGraspNet#1]
Hello! thanks for your excellent work!

I have one question:
I read that your dataset provides **Amodal Segmentation Masks** (occlusion masks). However, according to my understanding, the **Nvidia Isaac Sim Replicator** cannot generate the **Amodal Segmentation Masks for each occluded object**.  
May I ask how your team generated these  **Amodal Segmentation Masks**?
![Occlusion masks](https://user-images.githubusercontent.com/90683510/189301011-f4763dd1-1ab5-4906-b87a-3fb923c46932.png)

Thanks for your time!

**Comment by maximiliangilles** [comment]
Hi @Trav1slaflame,

you are right. We are generating amodal object masks with custom code we wrote specifically for this purpose. Isaac Sim does not support this ground truth mask. Our custom approach is based on visible segmentation masks and single object scenes.

Best,

Max

**Comment by Trav1slaflame** [comment]
Dear @maximiliangilles,

Thank you so much for your reply!

May I ask whether the custom code for generating amodal object masks is available in your repo?

Again, Thank you very much!

**Comment by maximiliangilles** [comment]
Hi @Trav1slaflame,

making the codebase public is intendet but unfortunately I cannot give you a firm date yet. We hope that we can shift our code base to a newer isaac sim version soon. If you have a specific question regarding how to generate amodal masks for your project, feel free to contact me via mail.

Best,

Max

**Comment by Trav1slaflame** [comment]
Dear @maximiliangilles,

Got it! Thank you so much!

**Comment by Cadodo97** [comment]
> Hi [@Trav1slaflame](https://github.com/Trav1slaflame),
> 
> making the codebase public is intendet but unfortunately I cannot give you a firm date yet. We hope that we can shift our code base to a newer isaac sim version soon. If you have a specific question regarding how to generate amodal masks for your project, feel free to contact me via email.
> 
> Best,
> 
> Max

Hi @maximiliangilles congrats for the amazing job, really really interesting. 
Can I contact you for some details about the generation of amodal mask and how you set the traparancy in Isaac Sym?

Thank you very much!
