### ISSUE TITLE
About the realease of baseline codes

### ISSUE THREAD

**Issue by paolotron** [maximiliangilles/MetaGraspNet#10]
In the last release of the MetaGraspNetv2 paper, several experiments have been reported on object detection, grasp generation, dependency graph generation etc... Will the code for this experiment be released?

**Comment by maximiliangilles** [comment]
Hi @paolotron,

Currently, there are no plans to release the experimental code. However, recently, I have been working on an updated version of our multi-modal data loader. I plan to release the code in the coming days. The data loader is designed to work seamlessly with both our synthetic and real-world data, providing a robust foundation for those who want to work with the dataset.
