### ISSUE TITLE
Missing GT Poses for MGN-Real

### ISSUE THREAD

**Issue by streckus** [maximiliangilles/MetaGraspNet#11]
Hi,
thanks for the great dataset. I wasn't able to find the ground truth poses for the real-world data. I understand these annotations are only provided for a subset of frames. For which frames are the ground truth poses provided and where do I find the pose annotations?
Best regards, Michael

**Comment by maximiliangilles** [comment]
Hi @streckus,

Let me check, I will get back to you shortly.

Best,

Maximilian

**Comment by streckus** [comment]
Hi @maximiliangilles ,

thank you for updating the dataset with the missing pose information. This resolves the issue :)

Best,
Michael
