### ISSUE TITLE
Finetuning on empty Bin

### ISSUE THREAD

**Issue by paolotron** [maximiliangilles/MetaGraspNet#13]
In the experiment section of the paper MetaGraspNetv2 you report experiments where you introduce finetuning on the empty bin, this scene isn't provided for the real dataset, could you add it?

**Comment by maximiliangilles** [comment]
Hi @paolotron,

thank you for noticing. Sure. You can download them under:

https://nx25922.your-storageshare.de/s/gDjoncpyD4K8XRy

Best,

Max
