### ISSUE TITLE
Object Id Dismatch in the MGN-SimV2

### ISSUE THREAD

**Issue by Yuchen-cyber** [maximiliangilles/MetaGraspNet#15]
Hi,

I am using the the object_id in the h5 files, I found a object id dismatch in scene 2027, number 17 image.

In the 17_scene.hdf5, I extract ['objects']['poses_relative_to_camera'], it gives me 4 4X4 positions. However, When I extract ['non_colliding_grasps']['paralleljaw']['object_id'], it gives me something like this: array([2., 2., 2., ..., 5., 5., 5.], dtype=float32). 2 is within the boundary of [0,3], but 5 is out of the boundary of the 'poses_relative_to_camera' list.

And below is the rgb image of scene 2027, number 17: 

![17_rgb](https://github.com/user-attachments/assets/0827fd80-36ec-4010-95d2-48bc2d32d88e)

From this image I could see 6 objects.

I am not sure if I misunderstand the object_id or the  poses_relative_to_camera in  the ground truth dataset, I did not find any explanation about this either in paper nor in the readme.

Could you check that? Thank you!

**Comment by maximiliangilles** [comment]
Hi,

I just had a look into into your issue. When I open the 17_scene.hdf5 file, it gives me an array of shape [6,4,4] - representing 6 objects with a T matrix of 4x4.

I am not sure how you open the files, I recommend using h5ls. 

Best,

Max

**Comment by Yuchen-cyber** [comment]
Hi,

Thank you for your reply!

I am sorry I give the wrong example, the 17_scene.hdf5 works fine on my end. I am so sorry for the confusion.

I use the command you give me:
```
h5ls -d 17_scene.hdf5/objects/poses_relative_to_camera
```
It gives me a shape of {6,4,4}.

However, other scenes like 2_scene.hdf5 and 14_scene.hdf5 have the problems of object id number out of the boundary of the poses_relative_to_camera list.

I will take 14_scene.hdf5 as an example:

I use the command:
```
h5ls -d 14_scene.hdf5/objects/poses_relative_to_camera
```

It gives the outputs:
```
poses_relative_to_camera Dataset {4, 4, 4}
    Data:
        (0,0,0) 0.811842, -0.320136, -0.488289, -1.27184, -0.558795, -0.183522, -0.808744, 6.63687,
        (0,2,0) 0.169296, 0.929426, -0.327881, 83.3889, 0, 0, 0, 1, -0.701749, 0.574669, 0.421074, -11.5908,
        (1,1,0) -0.324063, -0.783843, 0.529692, 2.60852, 0.634453, 0.235256, 0.73629, 85.2237, 0, 0, 0, 1,
        (2,0,0) 0.71895, -0.394321, -0.572384, -3.12126, -0.634829, -0.0372004, -0.771757, -3.38797,
        (2,2,0) 0.283027, 0.91822, -0.277071, 95.1836, 0, 0, 0, 1, 0.105739, -0.759132, -0.642291, -6.42305,
        (3,1,0) -0.324677, 0.584156, -0.743873, -8.68724, 0.939896, 0.287193, -0.184705, 91.8804, 0, 0, 0, 1

```
So the shape of the 'poses_relative_to_camera' list should be {4,4,4}.

Below is what I get using h5py:
```
>>> import h5py
>>> h = h5py.File('path/of/my/data/scene2027/14_scene.hdf5')
>>> len(h['objects']['poses_relative_to_camera'])
4
>>> h['non_colliding_grasps']['paralleljaw']['object_id'][:]
array([2., 2., 2., ..., 5., 5., 5.], dtype=float32)
```

So in this case, the index 5 here is out of boundary of a list with a length of 4.

From the image '14_rgb.png' below, I could only recognize 4 objects.
![14_rgb](https://github.com/user-attachments/assets/fc81d4f5-1d93-4797-9e18-8b768bc7a50e)

I am not sure if the object_id can be used like this way.

Thank you!

**Comment by Yuchen-cyber** [comment]
Hi Max,

Thank you for the reply!

Now the problem is fixed. I shall close this issue.

I also would like to provide how I solve my problem in case other people need it.

To retrieve the specific object position using the index, I first get the category number using the instance_id from ```non_colliding_grasps/paralleljaw/object_id```. The categories list is loaded from the 0_scene.hdf5 file. Then I use the category number value to find the index in other X_scene.hdf5 categories list in order to find the index of the position.

Thank you!

Best,
Yuchen
