### ISSUE TITLE
Download MetaGraspNetV2

### ISSUE THREAD

**Issue by chenchenzhen** [maximiliangilles/MetaGraspNet#16]
I am very interested in using the MetaGraspNetV2 dataset for my project. However, I am unable to find the download link and cannot access the download page.

Could you please provide me with the download link or any guidance on how to obtain the dataset? I appreciate your help and thank you for your work on this project!

**Comment by maximiliangilles** [comment]
Hi @chenchenzhen,

I am in contact with the cloud provider to fix this issue.

Best,

Maximilian

**Comment by chenchenzhen** [comment]
Hi Maximilian,

Thank you for the update! I appreciate your efforts in resolving this issue. Please let me know if there’s anything I can assist with on my end.

Looking forward to your reply.

Best regards,
Chenchen

**Comment by maximiliangilles** [comment]
Hi @chenchenzhen,

can you check if it works now? The issue should be resolved.

**Comment by chenchenzhen** [comment]
Hi maximiliangilles，

Thank you for your message. I’ve checked, and the issue has been resolved successfully.

Please let me know if you need any further assistance.

Best regards,
Chenchen
