### ISSUE TITLE
Missing Fields in Ground Truth

### ISSUE THREAD

**Issue by milenayahya** [maximiliangilles/MetaGraspNet#19]
Hello, thank you for your meticulous work. 
I need the data annotations, in particular I need the bounding boxes and categories. I tried to read the ".../scene*/*_scene.hdf5" in 3 different ways, and the content of these files is always:
camera
camera/pose_relative_to_world
objects
objects/categories

As opposed to the expected: 
 |>camera
       |>poses_relative_to_world
    |>keypts
      |>com
        |>keypts_relative_to_camera
        |>object_id
      |>byhand
        |>keypts_relative_to_camera
        |>object_id
        |>occluded_keypts_relative_to_camera
        |>occluded_object_id
    |>non_colliding_grasps
      |>paralleljaw
        |>contact_poses_relative_to_camera
        |>contact_width
        |>franka_poses_relative_to_camera
        |>object_id
        |>score_analytical
        |>score_simulation
        |>score_wrench
      |>suctioncup
        |>contact_poses_relative_to_camera
        |>object_id
        |>score_analytical
        |>score_simulation
        |>suction_poses_relative_to_camera
    |>objects
      |>bbox_loose
      |>categories
      |>poses_relative_to_camera
      
I downloaded version 2 of the dataset (Real) cited in the README. I browsed all the files in the dataset, and I can't seem to find the bounding boxes. Could you please provide any indication on where I could find the objects' bounding boxes?

**Comment by maximiliangilles** [comment]
Hi @milenayahya,

Thank you for your question! For detailed guidance on how to read in the ground truth, I recommend checking the source code of `./Scripts/visualize_2d.py`. It contains all the relevant information you'll need.

Please note that the 2D bounding boxes are not explicitly included in the dataset. However, they can be derived from the pixelwise instance segmentation masks provided.

Let me know if you have any further questions!

Best regards,
Max

**Comment by milenayahya** [comment]
Thank you @maximiliangilles for your prompt response. 

I am attempting to load the instance segmentation masks as suggested:
"""
 file_path = "C:\\Users\\cm03009\\Downloads\\data_ifl_16\\mnt\\data1\\data_ifl_real\\scene800\\52.npz"
    with np.load(file_path) as data:
        depth = data['depth']
        print(f"Depth: {depth}")
        try:
            instances_objects = data['instances_objects']
            print(f"Instances objects: {instances_objects}")
        except:
            print(f"WARNING : instances_objects not in file")
            instances_objects = np.zeros_like(depth)
        try:
            instances_semantic = data['instances_semantic']
        except:
            print(f"WARNING : instances_semantic not in file")
            instances_semantic = np.zeros_like(depth)
"""

However, all the values are 0s and nans.

> Depth: [[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]]
Instances objects: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Instances semantic: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

 I am using the [Link](https://nx25922.your-storageshare.de/s/HPe2eYGGJGz6rqd) provided in the README to download the dataset, and I've verified that it is not a downloading issue.

**Comment by maximiliangilles** [comment]
Can you paste here what python command you are running?
