### ISSUE TITLE
About the release of grasp sampling code 

### ISSUE THREAD

**Issue by SeungBack** [maximiliangilles/MetaGraspNet#2]
Hi @maximiliangilles, 

Thank you for sharing your amazing work! 
I am looking for the codes to generate grasp pose annotations for my custom objects, and your grasp sampling and evaluation process in IsaacGym would be greatly helpful for our project. 

When the grasp sampling codes will be released? (Customizing MetaGraspNet Section in README.md)

Thank you for your time.

**Comment by maximiliangilles** [comment]
Hi @SeungBack,

thanks for your interest in our work. Our internal goal is to publish with the proceeedings, but I hope that I can help you out earlier, probably this or next week. I would like to do run some additional tests, before uploading.

Best,

Maximilian Gilles

**Comment by maximiliangilles** [comment]
Hi @SeungBack,

code for generating parallel-jaw and vacuum grasps for custom objects is available. Scripts for parallel-jaw grasp evaluation in Isaac Gym will follow soon.

Best,

Maximilian Gilles

**Comment by SeungBack** [comment]
Big thanks for your contribution, and it will be greatly helpful for our project!
