### ISSUE TITLE
Some findings about the synthetic data

### ISSUE THREAD

**Issue by caijunhao** [maximiliangilles/MetaGraspNet#6]
First of all, thank you so much for contributing such a comprehensive dataset. 
However, I found that there are hundreds of synthetic scenes containing nothing in the tray (such as 325, 792, 1403 and so on). 
![blank tray](https://user-images.githubusercontent.com/22811702/236767466-021ddb21-ecdc-4ebd-9b80-b708a122c148.jpg)
Moreover, for some scenes like scene2243, the cracker box with object id 97 is not included in the given object models. 
I would like to know how can we use them. And if they are useless, it could be helpful if you can further do the data cleansing and add additional object models to the model list. 
Thank you so much for your time.

**Comment by maximiliangilles** [comment]
Hi @caijunhao,

they empty scenes are in the dataset for purpose. They can help to learn the background, however of course you can always exclude them in your custom data pipeline. With regard to your second question, I will upload a new version of the dataset in the next couple days, where we fixed some minor issues. The naming issue you mentioned will should be fixed too, in the meantime feel free to rename model '000' to '097' -> this should do it. 

Hope that this answers all your questions!

Best!

**Comment by caijunhao** [comment]
Hi @maximiliangilles ,
Thank you for your quick response. 
Renaming the model works for me.
Thank you for your help!
