### ISSUE TITLE
data set isnt visualizing 

### ISSUE THREAD

**Issue by Virat-IIITDWD** [maximiliangilles/MetaGraspNet#7]
(metagraspnet_env) vrn@vrn-OMEN-Laptop-15-en0xxx:~/MetaGraspNet$ python Scripts/visualize_2d.py --data_root ./dataset_sim --scene 8002 --viewpt 0 --visualize_layout
[ WARN:0@0.588] global loadsave.cpp:244 findDecoder imread_('dataset_sim/scene8002/0_rgb.png'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "Scripts/visualize_2d.py", line 60, in <module>
    color_img = cv2.cvtColor(color_bgr, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.7.0) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'

all the dataset are placed properly. except for scene 1557 none of the other are opening

**Comment by Virat-IIITDWD** [comment]
also can you please properly specify the required versions of all the dependencies like numpy

**Comment by maximiliangilles** [comment]
Hi @Virat-IIITDWD,

thanks for pointing that out. It looks like something went wrong with the paths, could specify your folder structure for me?

With regard to your 2nd question, in the 'environment.yml' file all packages are specified with version number, maybe this can be a starting point.

Best,

Max

**Comment by Virat-IIITDWD** [comment]
> Hi @Virat-IIITDWD,
> 
> thanks for pointing this out. It looks like something went wrong with the paths, could specify your folder structure for me?
> 
> With regard to your 2nd question, in the 'environment.yml' file all packages are specified with version number, maybe this can be a starting point.
> 
> Best,
> 
> Max

thank you for replying. things got resolved after i reinstalled numpy1.21.1
