### ISSUE TITLE
Corrupted files

### ISSUE THREAD

**Issue by enricivi** [maximiliangilles/MetaGraspNet#8]
Hello all,

First of all, I would like to thank you for this dataset. 

I downloaded the real part of the dataset, and I have found that some files are corrupted (like scene4\3_depth.png).  Could it be possible to check if the files are actually damaged, or if it is just a download problem?

Thank you in advance for your support.

[Update] I have the same problem with the synthetic part

**Comment by maximiliangilles** [comment]
Hi @enricivi,

can you specify how you try to load the images?

Best,

Maximilian

**Comment by enricivi** [comment]
I am just opening the png images with the default windows viewer (also tried with Python and Matplotlib). In some cases the software throws an error (corrupted or incomplete file).

**Comment by maximiliangilles** [comment]
Can you name me some files which do not work? I will check later, I haven't encountered this issue yet.

**Comment by enricivi** [comment]
Hello, sorry for the late reply.

As example, I have some problems with the following scene:

- Real -> scene4/3_depth.png
- Synth -> scene1604/36_rgb.png

Thanks for your help and patience.

**Comment by maximiliangilles** [comment]
Hi @enricivi,

I checked the files you specified and on my system I am able to open them. You could download them again and check?
